---
title: "gapminder-wrangle"
author: "Peng Zhang"
date: "7/9/2020"
output: html_document
---

```{r setup, message = F, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Learn `dplyr` using gapminder dataset

```{r}
gapminder <- read_csv('data/gapminder.csv')
#View(gapminder)
```
```{r}
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "China")
```

```{r}
filter(gapminder, country == "Mexico" & year == 2002)
```

```{r}
b1 <- filter(gapminder, country == 'Brazil', year >= 1987, year <= 2007)
mean(b1$lifeExp)
```
```{r}
gap_cambodia  <- gapminder %>% 
  filter(country == "Cambodia") %>%
  dplyr::select(-continent, -lifeExp)
```
```{r}
gapminder %>% filter(continent == 'Asia', year == 2007) %>% mutate(pop1000 = pop / 1000)
```
```{r}
gapminder %>%
  filter(year == 2002) %>%
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop))
```
```{r}
continent_pop <- gapminder %>%
  group_by(continent, year) %>%
  summarize(cont_pop = sum(pop))
continent_pop %>% ggplot(aes(x = year, y = cont_pop, col = continent))+
  geom_line()
```
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(cont_pop = sum(pop)) %>%
  arrange(year)
```
```{r}
gapdesc <- gapminder %>% arrange(desc(country))
gapdesc %>% filter(continent == 'Asia') %>% group_by(year) %>% summarize(maxlife = max(lifeExp)) %>% arrange(desc(year)) %>% ungroup()
```

